<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <PublishAot>true</PublishAot>
        <Platforms>AnyCPU;x86</Platforms>
        <StartupObject></StartupObject>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
      <DefineConstants>$(DefineConstants);CONSOLE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|x86'">
      <DefineConstants>$(DefineConstants);CONSOLE</DefineConstants>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'" />

    <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|x86'" />

    <ItemGroup>
      <PackageReference Include="System.Text.Encoding.CodePages" Version="9.0.0" />
    </ItemGroup>

</Project>
